version: "3.9"
services:
  auth-service:
    build: ./auth-service
    environment:
      - JWT_SECRET=changeme
    ports:
      - "8081:8081"

  wallet-service:
    build: ./wallet-service
    ports:
      - "8082:8082"

  transaction-service:
    build: ./transaction-service
    ports:
      - "8083:8083"

  cashapp-proxy:
    build: ./cashapp-proxy
    ports:
      - "8084:8084"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - wallet-service
      - transaction-service
      - cashapp-proxy
