services:
  - name: auth-service
    type: docker
    dockerfile_path: ./auth-service/Dockerfile
    context: ./auth-service
    env:
      - key: JWT_SECRET
        value: ${JWT_SECRET}
    ports:
      - 8081

  - name: wallet-service
    type: docker
    dockerfile_path: ./wallet-service/Dockerfile
    context: ./wallet-service
    ports:
      - 8082

  - name: transaction-service
    type: docker
    dockerfile_path: ./transaction-service/Dockerfile
    context: ./transaction-service
    ports:
      - 8083

  - name: cashapp-proxy
    type: docker
    dockerfile_path: ./cashapp-proxy/Dockerfile
    context: ./cashapp-proxy
    ports:
      - 8084

  - name: nginx
    type: docker
    dockerfile_path: ./nginx/Dockerfile
    context: ./nginx
    ports:
      - 80
    depends_on:
      - auth-service
      - wallet-service
      - transaction-service
      - cashapp-proxy
